qtscript: add fix for build with gcc 8.3
* fixes issue introduced with gcc upgrade to 8.3:

| /OE/build/luneos-master/webos-ports/tmp-glibc/work/i586-webos-linux/qtscript/5.12.0+gitAUTOINC+0be84da600-r0/git/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp:157:5: error: expected '(' before 'volatile'
|  asm volatile (
|      ^~~~~~~~
|      (
| /OE/build/luneos-master/webos-ports/tmp-glibc/work/i586-webos-linux/qtscript/5.12.0+gitAUTOINC+0be84da600-r0/git/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp:158:1: error: expected unqualified-id before string constant
|  ".globl " SYMBOL_STRING(ctiOpThrowNotCaught) "\n"
|  ^~~~~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>